repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: detect-private-key
        priority: 0
      - id: end-of-file-fixer
        types: [python]
        priority: 1
      - id: fix-byte-order-marker
        priority: 2
      - id: mixed-line-ending
        args: [--fix=lf]
        types: [python]
        priority: 3
      - id: trailing-whitespace
        priority: 4

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
        priority: 0

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-tabs
        priority: 0
      - id: remove-tabs
        args: [--whitespaces-count, '2']
        priority: 5
      - id: chmod
        args: ['644']
        exclude_types: [shell]
        exclude: ^(.*__main__\.py|horizon/backend/export_openapi_schema\.py|horizon/backend/scripts/manage_admins\.py)$
        priority: 6
      - id: chmod
        args: ['755']
        types: [shell]
        priority: 6
      - id: chmod
        args: ['755']
        files: ^(.*__main__\.py|horizon/backend/export_openapi_schema\.py|horizon/backend/scripts/manage_admins\.py)$
        priority: 6
      - id: insert-license
        types: [python]
        exclude: ^(horizon/backend/dependencies/stub.py|docs/.*\.py|tests/.*\.py)$
        args:
          - --license-filepath
          - .spdx-license-header.txt
          - --allow-past-years
          - --no-extra-eol
        priority: 7

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2']
        priority: 7

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args: [-w]
        additional_dependencies:
          - tomli
        exclude: .*\.svg
        priority: 8

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.10
    hooks:
      - id: uv-lock
        priority: 9

  - repo: local
    hooks:
      - id: towncrier
        name: towncrier
        entry: towncrier build --draft
        language: system
        types: [markdown]
        pass_filenames: false
        priority: 9

      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format .
        types: [python]
        pass_filenames: false
        priority: 9

      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check --fix
        types: [python]
        pass_filenames: false
        priority: 10

      - id: mypy
        name: mypy
        entry: mypy horizon
        language: python
        types: [python]
        require_serial: true
        pass_filenames: false
        priority: 10

  - repo: meta
    hooks:
      - id: check-hooks-apply
        priority: 0
      - id: check-useless-excludes
        priority: 0

ci:
  skip:
    - mypy  # checked with Github Actions
    - chmod  # failing in pre-commit.ci
    - docker-compose-check  # cannot run on pre-commit.ci
    - ruff-format # checked with Github Actions
    - ruff-check # checked with Github Actions
    - towncrier # checked with Github Actions
