version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  jobs:
    post_create_environment:
      - pip install poetry
      - pip install sphinx-plantuml # remove after https://github.com/zqmillet/sphinx-plantuml/pull/4
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-root --extras backend --extras client-sync --with dev,docs


sphinx:
  configuration: docs/conf.py
