version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
  apt_packages:
    - libldap2-dev
    - libsasl2-dev
  jobs:
    post_create_environment:
      - pip install poetry
      - pip install sphinx-plantuml # remove after https://github.com/zqmillet/sphinx-plantuml/pull/4
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-root --all-extras --with docs --without dev,test
# TODO: add openapi.json schema generation

sphinx:
  configuration: docs/conf.py
