version: '3.9'
services:
  db:
    image: central-mirror.services.mts.ru/postgres:15-alpine
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    image: sregistry.mts.ru/onetools/bigdata/platform/onetools/horizon/backend:${TAG:-develop}
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/monitoring/ping
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
