services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3

  backend:
    image: mtsrus/horizon-backend:${TAG:-develop}
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: prod
      network: host
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./:/app

  ldap:
    image: thoteam/slapd-server-mock
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 389:389
      - 636:636

volumes:
  postgres_data:
