services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: horizon
      POSTGRES_USER: horizon
      POSTGRES_PASSWORD: 123UsedForTestOnly
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3

  backend:
    image: mtsrus/horizon-backend:${VERSION:-develop}
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: prod
      network: host
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./horizon:/app/horizon
      - ./docs/_static:/app/docs/_static
      - ./reports:/app/reports
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml

  ldap:
    image: thoteam/slapd-server-mock
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 389:389
      - 636:636

volumes:
  postgres_data:
