FROM python:3.12-slim as test
LABEL maintainer="DataOps.ETL"

RUN apt-get update && apt-get install -y \
        libkrb5-dev \
        libsasl2-dev \
        libsasl2-modules-gssapi-mit \
        libsasl2-modules-ldap \
        libsasl2-modules \
        libssl-dev \
        libldap2-dev \
        autoconf \
        gcc \
        g++ \
        make \
        libnghttp2-dev \
        libffi-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app
ENV PYTHONPATH=/app

RUN set +x\
    && pip install poetry \
    && poetry config virtualenvs.create false \
    # https://github.com/python-poetry/poetry/issues/6705
    && export POETRY_CONFIG=$(python -c 'from poetry.locations import CONFIG_DIR; print(CONFIG_DIR)') \
    && cd $POETRY_CONFIG \
    && poetry init --name poetry-instance \
    && if [[ "x${PYTHON_VERSION}" != "x3.7" ]]; then \
        poetry self add poetry-bumpversion; \
       fi

COPY ./pyproject.toml ./poetry.lock* ./

# TODO: remove sphinx-plantuml install after solving https://github.com/zqmillet/sphinx-plantuml/pull/4
RUN poetry install \
        --no-root \
        --all-extras \
        --with dev,test,docs && \
    pip install sphinx-plantuml --no-deps

ARG PYDANTIC_VERSION=2
RUN if [[ "x${PYDANTIC_VERSION}" == "x1" ]]; then \
        # pydantic-settings depends in pydantic>2.3, so delete it
        # urllib3 v1 lack some options from v2, test it too
        pip uninstall -y "pydantic-settings"; \
        pip install "pydantic<2" "autodoc-pydantic<2" "urllib3<2.0"; \
    fi
