ARG PYTHON_VERSION=3.11
FROM sregistry.mts.ru/bigdata/platform/docker-images/python:${PYTHON_VERSION}-slim as test

RUN microdnf -y install \
        krb5-libs \
        krb5-workstation \
        krb5-devel \
        cyrus-sasl \
        cyrus-sasl-devel \
        cyrus-sasl-gssapi \
        cyrus-sasl-ldap \
        cyrus-sasl-plain \
        openldap-devel \
        openssl-devel \
        autoconf \
        gcc \
        gcc-c++ \
        make

WORKDIR /app
ENV PYTHONPATH=/app

RUN set +x\
    && pip install poetry \
    && poetry config virtualenvs.create false \
    # https://github.com/python-poetry/poetry/issues/6705
    && export POETRY_CONFIG=$(python -c 'from poetry.locations import CONFIG_DIR; print(CONFIG_DIR)') \
    && cd $POETRY_CONFIG \
    && poetry init --name poetry-instance \
    && poetry source add --priority=default nexus https://nexus.services.mts.ru/repository/pip/simple \
    && poetry self add poetry-bumpversion

COPY ./pyproject.toml ./poetry.lock* ./

RUN poetry install \
        --no-root \
        --all-extras \
        --with dev,test
