# SPDX-FileCopyrightText: 2023-2024 MTS (Mobile Telesystems)
# SPDX-License-Identifier: Apache-2.0
"""empty message

Revision ID: 92f3992740eb
Revises: 4bc3fffc0209
Create Date: 2024-02-20 19:27:04.590232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92f3992740eb"
down_revision = "4bc3fffc0209"
branch_labels = None
depends_on = None

enum_name = "actionenum"
enum_values = ("CREATED", "UPDATED", "DELETED")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hwm", "is_deleted")
    actionenum = sa.Enum(*enum_values, name=enum_name)
    actionenum.create(op.get_bind())
    op.add_column("hwm_history", sa.Column("action", actionenum, nullable=False))

    op.drop_constraint("fk__hwm_history__hwm_id__hwm", "hwm_history", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk__hwm_history__hwm_id__hwm", "hwm_history", "hwm", ["hwm_id"], ["id"], ondelete="CASCADE")
    op.drop_column("hwm_history", "action")
    op.execute("DROP TYPE %s;" % enum_name)
    op.add_column("hwm", sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
