# SPDX-FileCopyrightText: 2023-2024 MTS (Mobile Telesystems)
# SPDX-License-Identifier: Apache-2.0
"""Add action to HWMHistory

Revision ID: 1470fe0dceb6
Revises: 4bc3fffc0209
Create Date: 2024-02-22 10:48:56.102769

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1470fe0dceb6"
down_revision = "4bc3fffc0209"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hwm", "is_deleted")
    op.add_column("hwm_history", sa.Column("action", sa.String(length=255), nullable=False))
    op.drop_constraint("fk__hwm_history__hwm_id__hwm", "hwm_history", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk__hwm_history__hwm_id__hwm", "hwm_history", "hwm", ["hwm_id"], ["id"], ondelete="CASCADE")
    op.drop_column("hwm_history", "action")
    op.add_column("hwm", sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
